global using System.Globalization;
global using System.Net;
global using System.Text.Json;
global using Microsoft.AspNetCore.Mvc;
global using AutoMapper;
global using CRUD.WebAPI.Entities;
global using CRUD.WebAPI.Helpers;
global using CRUD.WebAPI.Models.Users;
global using CRUD.WebAPI.Services;